language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

before_script:
  - hostname
  - mysql -e 'create database phototresor_test;'
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev
  - chmod -R 777 app/storage/
  - php artisan migrate --seed --env=travis
  - php artisan serve --env=travis &
  - sleep 5 # give it some time to start
  - php vendor/bin/codecept build

script:
  - php vendor/bin/codecept run

after_failure:
  - cat app/storage/logs/laravel.log
  - cat tests/_output/*
